### PR TITLE
fix compatibility issue with gob registrations

### LINKED ISSUE #24: gob: name not registered for interface
A migration to the `"cloud.google.com/go/bigtable/admin/apiv2/adminpb"` package caused gob decoding issues with data originally encoded before the migration.

```bash
sql_tables.go:81: sql: Scan error on column index 2, name "metadata": gob: name not registered for interface: "*admin.GcRule_MaxNumVersions"
```

To fix this, we need to register the types with name that is consistent with the original registrations pre-migration (`*admin.`). More discussion on this in [this PR](https://github.com/bitly/little_bigtable/pull/22).

### PR DESCRIPTION
**Pull request by zoemccormick**
Resolves #24 

Fixes an unreleased change in master from #18 that introduced some incompatibility issues with decoding data with gob. Registers the new types with gob using `RegisterName` to maintain compatibility with existing data.

Original discussion in [this PR](https://github.com/bitly/little_bigtable/pull/22)

### CODE REVIEW

File: bttest/inmem.go [hunk 1]
```diff
@@ -1464,10 +1464,11 @@ func (r *row) String() string {
 var gcTypeWarn sync.Once
 
 func init() {
-	gob.Register(&btapb.GcRule_Intersection_{})
-	gob.Register(&btapb.GcRule_Union_{})
-	gob.Register(&btapb.GcRule_MaxAge{})
-	gob.Register(&btapb.GcRule_MaxNumVersions{})
+	gob.RegisterName("*admin.GcRule_Intersection_", &btapb.GcRule_Intersection_{})
```
Comment (jehiah) [inline bttest/inmem.go:1468]: Can you add a code comment pointing to this issue on why these have a custom name?

**Review by jehiah — APPROVED** [review]
